################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

C++M_SRCS := 
CPP_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
ELF_SRCS := 
C_UPPER_SRCS := 
CXX_SRCS := 
CCM_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
CC_SRCS := 
C_SRCS := 
CXXM_SRCS := 
CYCLO_FILES := 
OBJDUMP_LIST := 
CCM_DEPS := 
C_UPPER_DEPS := 
S_DEPS := 
CXXM_DEPS := 
C_DEPS := 
OBJCOPY_BIN := 
CC_DEPS := 
SIZE_OUTPUT := 
C++_DEPS := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
CXX_DEPS := 
MAP_FILES := 
S_UPPER_DEPS := 
C++M_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Core/Src \
Core \
Drivers/BSP/Components/ism330dhcx \
Drivers/BSP/Components/s25fl128s \
Drivers/BSP/Components/ssd1315 \
Drivers/BSP/Components/stm32wb_at \
Drivers/BSP/Components/stts22h \
Drivers/BSP/STM32WB5MM-DK \
Drivers/CMSIS/Core/Template/ARMv8-M \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/JTest/src \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/platform/ARMCC \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/platform/ARMCLANG \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/platform/GCC \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/platform \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/basic_math_tests \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/complex_math_tests \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/controller_tests \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/fast_math_tests \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/filtering_tests \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/intrinsics_tests \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/matrix_tests \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/statistics_tests \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/support_tests \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/transform_tests \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/DspLibTest_FVP_A5/RTE/CMSIS \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/DspLibTest_FVP_A5/RTE/Device/ARMCA5 \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/DspLibTest_FVP_A5 \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/BasicMathFunctions \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/ComplexMathFunctions \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/ControllerFunctions \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/FastMathFunctions \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/FilteringFunctions \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/HelperFunctions \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/Intrinsics \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/MatrixFunctions \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/StatisticsFunctions \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/SupportFunctions \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/TransformFunctions \
Drivers/CMSIS/DSP/Examples/ARM/arm_class_marks_example/RTE/Device/ARMCM0 \
Drivers/CMSIS/DSP/Examples/ARM/arm_class_marks_example/RTE/Device/ARMCM3 \
Drivers/CMSIS/DSP/Examples/ARM/arm_class_marks_example/RTE/Device/ARMCM4_FP \
Drivers/CMSIS/DSP/Examples/ARM/arm_class_marks_example/RTE/Device/ARMCM7_SP \
Drivers/CMSIS/DSP/Examples/ARM/arm_class_marks_example \
Drivers/CMSIS/DSP/Examples/ARM/arm_convolution_example/RTE/Device/ARMCM0 \
Drivers/CMSIS/DSP/Examples/ARM/arm_convolution_example/RTE/Device/ARMCM3 \
Drivers/CMSIS/DSP/Examples/ARM/arm_convolution_example/RTE/Device/ARMCM4_FP \
Drivers/CMSIS/DSP/Examples/ARM/arm_convolution_example/RTE/Device/ARMCM7_SP \
Drivers/CMSIS/DSP/Examples/ARM/arm_convolution_example \
Drivers/CMSIS/DSP/Examples/ARM/arm_dotproduct_example/RTE/Device/ARMCM0 \
Drivers/CMSIS/DSP/Examples/ARM/arm_dotproduct_example/RTE/Device/ARMCM3 \
Drivers/CMSIS/DSP/Examples/ARM/arm_dotproduct_example/RTE/Device/ARMCM4_FP \
Drivers/CMSIS/DSP/Examples/ARM/arm_dotproduct_example/RTE/Device/ARMCM7_SP \
Drivers/CMSIS/DSP/Examples/ARM/arm_dotproduct_example \
Drivers/CMSIS/DSP/Examples/ARM/arm_fft_bin_example/RTE/Device/ARMCM0 \
Drivers/CMSIS/DSP/Examples/ARM/arm_fft_bin_example/RTE/Device/ARMCM3 \
Drivers/CMSIS/DSP/Examples/ARM/arm_fft_bin_example/RTE/Device/ARMCM4_FP \
Drivers/CMSIS/DSP/Examples/ARM/arm_fft_bin_example/RTE/Device/ARMCM7_SP \
Drivers/CMSIS/DSP/Examples/ARM/arm_fft_bin_example \
Drivers/CMSIS/DSP/Examples/ARM/arm_fir_example/RTE/Device/ARMCM0 \
Drivers/CMSIS/DSP/Examples/ARM/arm_fir_example/RTE/Device/ARMCM3 \
Drivers/CMSIS/DSP/Examples/ARM/arm_fir_example/RTE/Device/ARMCM4_FP \
Drivers/CMSIS/DSP/Examples/ARM/arm_fir_example/RTE/Device/ARMCM7_SP \
Drivers/CMSIS/DSP/Examples/ARM/arm_fir_example \
Drivers/CMSIS/DSP/Examples/ARM/arm_graphic_equalizer_example/RTE/Device/ARMCM0 \
Drivers/CMSIS/DSP/Examples/ARM/arm_graphic_equalizer_example/RTE/Device/ARMCM3 \
Drivers/CMSIS/DSP/Examples/ARM/arm_graphic_equalizer_example/RTE/Device/ARMCM4_FP \
Drivers/CMSIS/DSP/Examples/ARM/arm_graphic_equalizer_example/RTE/Device/ARMCM7_SP \
Drivers/CMSIS/DSP/Examples/ARM/arm_graphic_equalizer_example \
Drivers/CMSIS/DSP/Examples/ARM/arm_linear_interp_example/RTE/Device/ARMCM0 \
Drivers/CMSIS/DSP/Examples/ARM/arm_linear_interp_example/RTE/Device/ARMCM3 \
Drivers/CMSIS/DSP/Examples/ARM/arm_linear_interp_example/RTE/Device/ARMCM4_FP \
Drivers/CMSIS/DSP/Examples/ARM/arm_linear_interp_example/RTE/Device/ARMCM7_SP \
Drivers/CMSIS/DSP/Examples/ARM/arm_linear_interp_example \
Drivers/CMSIS/DSP/Examples/ARM/arm_matrix_example/RTE/Device/ARMCM0 \
Drivers/CMSIS/DSP/Examples/ARM/arm_matrix_example/RTE/Device/ARMCM3 \
Drivers/CMSIS/DSP/Examples/ARM/arm_matrix_example/RTE/Device/ARMCM4_FP \
Drivers/CMSIS/DSP/Examples/ARM/arm_matrix_example/RTE/Device/ARMCM7_SP \
Drivers/CMSIS/DSP/Examples/ARM/arm_matrix_example \
Drivers/CMSIS/DSP/Examples/ARM/arm_signal_converge_example/RTE/Device/ARMCM0 \
Drivers/CMSIS/DSP/Examples/ARM/arm_signal_converge_example/RTE/Device/ARMCM3 \
Drivers/CMSIS/DSP/Examples/ARM/arm_signal_converge_example/RTE/Device/ARMCM4_FP \
Drivers/CMSIS/DSP/Examples/ARM/arm_signal_converge_example/RTE/Device/ARMCM7_SP \
Drivers/CMSIS/DSP/Examples/ARM/arm_signal_converge_example \
Drivers/CMSIS/DSP/Examples/ARM/arm_sin_cos_example/RTE/Device/ARMCM0 \
Drivers/CMSIS/DSP/Examples/ARM/arm_sin_cos_example/RTE/Device/ARMCM3 \
Drivers/CMSIS/DSP/Examples/ARM/arm_sin_cos_example/RTE/Device/ARMCM4_FP \
Drivers/CMSIS/DSP/Examples/ARM/arm_sin_cos_example/RTE/Device/ARMCM7_SP \
Drivers/CMSIS/DSP/Examples/ARM/arm_sin_cos_example \
Drivers/CMSIS/DSP/Examples/ARM/arm_variance_example/RTE/Device/ARMCM0 \
Drivers/CMSIS/DSP/Examples/ARM/arm_variance_example/RTE/Device/ARMCM3 \
Drivers/CMSIS/DSP/Examples/ARM/arm_variance_example/RTE/Device/ARMCM4_FP \
Drivers/CMSIS/DSP/Examples/ARM/arm_variance_example/RTE/Device/ARMCM7_SP \
Drivers/CMSIS/DSP/Examples/ARM/arm_variance_example \
Drivers/CMSIS/DSP/PythonWrapper/cmsisdsp_pkg/src \
Drivers/CMSIS/DSP/Source/BasicMathFunctions \
Drivers/CMSIS/DSP/Source/CommonTables \
Drivers/CMSIS/DSP/Source/ComplexMathFunctions \
Drivers/CMSIS/DSP/Source/ControllerFunctions \
Drivers/CMSIS/DSP/Source/FastMathFunctions \
Drivers/CMSIS/DSP/Source/FilteringFunctions \
Drivers/CMSIS/DSP/Source/MatrixFunctions \
Drivers/CMSIS/DSP/Source/StatisticsFunctions \
Drivers/CMSIS/DSP/Source/SupportFunctions \
Drivers/CMSIS/DSP/Source/TransformFunctions \
Drivers/CMSIS/Device/ST/STM32WBxx/Source/Templates/arm \
Drivers/CMSIS/Device/ST/STM32WBxx/Source/Templates/gcc \
Drivers/CMSIS/Device/ST/STM32WBxx/Source/Templates/iar \
Drivers/CMSIS/Device/ST/STM32WBxx/Source/Templates \
Drivers/CMSIS/NN/Examples/ARM/arm_nn_examples/cifar10/RTE/Device/ARMCM0 \
Drivers/CMSIS/NN/Examples/ARM/arm_nn_examples/cifar10/RTE/Device/ARMCM3 \
Drivers/CMSIS/NN/Examples/ARM/arm_nn_examples/cifar10/RTE/Device/ARMCM4_FP \
Drivers/CMSIS/NN/Examples/ARM/arm_nn_examples/cifar10/RTE/Device/ARMCM7_SP \
Drivers/CMSIS/NN/Examples/ARM/arm_nn_examples/cifar10 \
Drivers/CMSIS/NN/Examples/ARM/arm_nn_examples/gru/RTE/Device/ARMCM0 \
Drivers/CMSIS/NN/Examples/ARM/arm_nn_examples/gru/RTE/Device/ARMCM3 \
Drivers/CMSIS/NN/Examples/ARM/arm_nn_examples/gru/RTE/Device/ARMCM4_FP \
Drivers/CMSIS/NN/Examples/ARM/arm_nn_examples/gru/RTE/Device/ARMCM7_SP \
Drivers/CMSIS/NN/Examples/ARM/arm_nn_examples/gru \
Drivers/CMSIS/NN/Examples/IAR/iar_nn_examples/NN-example-cifar10 \
Drivers/CMSIS/NN/Examples/IAR/iar_nn_examples/NN-example-gru \
Drivers/CMSIS/NN/NN_Lib_Tests/nn_test/RTE/Device/ARMCM0 \
Drivers/CMSIS/NN/NN_Lib_Tests/nn_test/RTE/Device/ARMCM3 \
Drivers/CMSIS/NN/NN_Lib_Tests/nn_test/RTE/Device/ARMCM4 \
Drivers/CMSIS/NN/NN_Lib_Tests/nn_test/RTE/Device/ARMCM4_FP \
Drivers/CMSIS/NN/NN_Lib_Tests/nn_test/RTE/Device/ARMCM7_SP \
Drivers/CMSIS/NN/NN_Lib_Tests/nn_test/RTE/Device/STM32F411RETx \
Drivers/CMSIS/NN/NN_Lib_Tests/nn_test/Ref_Implementations \
Drivers/CMSIS/NN/NN_Lib_Tests/nn_test \
Drivers/CMSIS/NN/Source/ActivationFunctions \
Drivers/CMSIS/NN/Source/ConvolutionFunctions \
Drivers/CMSIS/NN/Source/FullyConnectedFunctions \
Drivers/CMSIS/NN/Source/NNSupportFunctions \
Drivers/CMSIS/NN/Source/PoolingFunctions \
Drivers/CMSIS/NN/Source/SoftmaxFunctions \
Drivers/CMSIS/RTOS2/Source \
Drivers/CMSIS/RTOS2/Template \
Drivers/STM32WBxx_HAL_Driver/Src \
Matter/Src \
Matter \
Middlewares/ST/STM32_WPAN/ble/core/auto \
Middlewares/ST/STM32_WPAN/ble/core/template \
Middlewares/ST/STM32_WPAN/ble/menu \
Middlewares/ST/STM32_WPAN/ble/mesh/MeshModel/Src \
Middlewares/ST/STM32_WPAN/ble/mesh/PAL/STM32WB \
Middlewares/ST/STM32_WPAN/ble/mesh/Src \
Middlewares/ST/STM32_WPAN/ble/svc/Src \
Middlewares/ST/STM32_WPAN/ble_lld/hal \
Middlewares/ST/STM32_WPAN/ble_lld/lld \
Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/lhci \
Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci \
Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl \
Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/vcp \
Middlewares/ST/STM32_WPAN/mac_802_15_4/core/src \
Middlewares/ST/STM32_WPAN/thread/openthread/core/openthread_api \
Middlewares/ST/STM32_WPAN/thread/openthread/stack/examples/apps/cli \
Middlewares/ST/STM32_WPAN/thread/openthread/stack/examples/apps/ncp \
Middlewares/ST/STM32_WPAN/thread/openthread/stack/examples/platforms/utils \
Middlewares/ST/STM32_WPAN/thread/openthread/stack/src/cli \
Middlewares/ST/STM32_WPAN/thread/openthread/stack/src/core/api \
Middlewares/ST/STM32_WPAN/thread/openthread/stack/src/core/backbone_router \
Middlewares/ST/STM32_WPAN/thread/openthread/stack/src/core/border_router \
Middlewares/ST/STM32_WPAN/thread/openthread/stack/src/core/coap \
Middlewares/ST/STM32_WPAN/thread/openthread/stack/src/core/common \
Middlewares/ST/STM32_WPAN/thread/openthread/stack/src/core/crypto \
Middlewares/ST/STM32_WPAN/thread/openthread/stack/src/core/diags \
Middlewares/ST/STM32_WPAN/thread/openthread/stack/src/core/mac \
Middlewares/ST/STM32_WPAN/thread/openthread/stack/src/core/meshcop \
Middlewares/ST/STM32_WPAN/thread/openthread/stack/src/core/net \
Middlewares/ST/STM32_WPAN/thread/openthread/stack/src/core/radio \
Middlewares/ST/STM32_WPAN/thread/openthread/stack/src/core/thread \
Middlewares/ST/STM32_WPAN/thread/openthread/stack/src/core/utils \
Middlewares/ST/STM32_WPAN/thread/openthread/stack/src/lib/hdlc \
Middlewares/ST/STM32_WPAN/thread/openthread/stack/src/lib/platform \
Middlewares/ST/STM32_WPAN/thread/openthread/stack/src/lib/spinel \
Middlewares/ST/STM32_WPAN/thread/openthread/stack/src/ncp \
Middlewares/ST/STM32_WPAN/thread/openthread/stack/third_party/mbedtls/repo/library \
Middlewares/ST/STM32_WPAN/thread/openthread/stack/third_party/tcplp/bsdtcp/cc \
Middlewares/ST/STM32_WPAN/thread/openthread/stack/third_party/tcplp/bsdtcp \
Middlewares/ST/STM32_WPAN/thread/openthread/stack/third_party/tcplp/lib \
Middlewares/ST/STM32_WPAN/utilities \
Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS \
Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 \
Middlewares/Third_Party/FreeRTOS/Source \
Middlewares/Third_Party/FreeRTOS/Source/portable/Common \
Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM0 \
Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM23/non_secure \
Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM23/secure \
Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM23_NTZ/non_secure \
Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM3 \
Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33/non_secure \
Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33/secure \
Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure \
Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM3_MPU \
Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F \
Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4_MPU \
Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 \
Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7_MPU/r0p1 \
Middlewares/Third_Party/FreeRTOS/Source/portable/IAR/ARM_CM0 \
Middlewares/Third_Party/FreeRTOS/Source/portable/IAR/ARM_CM23/non_secure \
Middlewares/Third_Party/FreeRTOS/Source/portable/IAR/ARM_CM23/secure \
Middlewares/Third_Party/FreeRTOS/Source/portable/IAR/ARM_CM23_NTZ/non_secure \
Middlewares/Third_Party/FreeRTOS/Source/portable/IAR/ARM_CM3 \
Middlewares/Third_Party/FreeRTOS/Source/portable/IAR/ARM_CM33/non_secure \
Middlewares/Third_Party/FreeRTOS/Source/portable/IAR/ARM_CM33/secure \
Middlewares/Third_Party/FreeRTOS/Source/portable/IAR/ARM_CM33_NTZ/non_secure \
Middlewares/Third_Party/FreeRTOS/Source/portable/IAR/ARM_CM4F \
Middlewares/Third_Party/FreeRTOS/Source/portable/IAR/ARM_CM4_MPU \
Middlewares/Third_Party/FreeRTOS/Source/portable/IAR/ARM_CM7/r0p1 \
Middlewares/Third_Party/FreeRTOS/Source/portable/IAR/ARM_CM7_MPU/r0p1 \
Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang \
Middlewares/Third_Party/FreeRTOS/Source/portable/RVDS/ARM_CM0 \
Middlewares/Third_Party/FreeRTOS/Source/portable/RVDS/ARM_CM3 \
Middlewares/Third_Party/FreeRTOS/Source/portable/RVDS/ARM_CM4F \
Middlewares/Third_Party/FreeRTOS/Source/portable/RVDS/ARM_CM4_MPU \
Middlewares/Third_Party/FreeRTOS/Source/portable/RVDS/ARM_CM7/r0p1 \
Middlewares/Third_Party/FreeRTOS/Source/portable/RVDS/ARM_CM7_MPU/r0p1 \
Middlewares/Third_Party/FreeRTOS/Source/portable/Tasking/ARM_CM4F \
Middlewares/Third_Party/connectedhomeip/devices/Thread/BME280-app/zap_generated \
Middlewares/Third_Party/connectedhomeip/src/access \
Middlewares/Third_Party/connectedhomeip/src/access/examples \
Middlewares/Third_Party/connectedhomeip/src/access/tests \
Middlewares/Third_Party/connectedhomeip/src/ble \
Middlewares/Third_Party/connectedhomeip/src/ble/tests \
Middlewares/Third_Party/connectedhomeip/src/controller \
Middlewares/Third_Party/connectedhomeip/src/controller/java \
Middlewares/Third_Party/connectedhomeip/src/controller/java/zap-generated \
Middlewares/Third_Party/connectedhomeip/src/controller/python \
Middlewares/Third_Party/connectedhomeip/src/controller/python/chip/ble \
Middlewares/Third_Party/connectedhomeip/src/controller/python/chip/clusters \
Middlewares/Third_Party/connectedhomeip/src/controller/python/chip/credentials \
Middlewares/Third_Party/connectedhomeip/src/controller/python/chip/crypto \
Middlewares/Third_Party/connectedhomeip/src/controller/python/chip/discovery \
Middlewares/Third_Party/connectedhomeip/src/controller/python/chip/interaction_model \
Middlewares/Third_Party/connectedhomeip/src/controller/python/chip/internal \
Middlewares/Third_Party/connectedhomeip/src/controller/python/chip/logging \
Middlewares/Third_Party/connectedhomeip/src/controller/python/chip/native \
Middlewares/Third_Party/connectedhomeip/src/controller/python/chip/server \
Middlewares/Third_Party/connectedhomeip/src/controller/python/chip/setup_payload \
Middlewares/Third_Party/connectedhomeip/src/controller/python/chip/tracing \
Middlewares/Third_Party/connectedhomeip/src/controller/python/chip/utils \
Middlewares/Third_Party/connectedhomeip/src/controller/tests \
Middlewares/Third_Party/connectedhomeip/src/controller/tests/data_model \
Middlewares/Third_Party/connectedhomeip/src/credentials \
Middlewares/Third_Party/connectedhomeip/src/credentials/attestation_verifier \
Middlewares/Third_Party/connectedhomeip/src/credentials/examples \
Middlewares/Third_Party/connectedhomeip/src/credentials/tests \
Middlewares/Third_Party/connectedhomeip/src/crypto \
Middlewares/Third_Party/connectedhomeip/src/crypto/tests \
Middlewares/Third_Party/connectedhomeip/src/include/platform/internal \
Middlewares/Third_Party/connectedhomeip/src/inet \
Middlewares/Third_Party/connectedhomeip/src/inet/tests \
Middlewares/Third_Party/connectedhomeip/src/lib/address_resolve \
Middlewares/Third_Party/connectedhomeip/src/lib/address_resolve/tests \
Middlewares/Third_Party/connectedhomeip/src/lib/asn1 \
Middlewares/Third_Party/connectedhomeip/src/lib/asn1/tests \
Middlewares/Third_Party/connectedhomeip/src/lib/core \
Middlewares/Third_Party/connectedhomeip/src/lib/core/tests \
Middlewares/Third_Party/connectedhomeip/src/lib/dnssd \
Middlewares/Third_Party/connectedhomeip/src/lib/dnssd/minimal_mdns \
Middlewares/Third_Party/connectedhomeip/src/lib/dnssd/minimal_mdns/core \
Middlewares/Third_Party/connectedhomeip/src/lib/dnssd/minimal_mdns/core/tests \
Middlewares/Third_Party/connectedhomeip/src/lib/dnssd/minimal_mdns/records \
Middlewares/Third_Party/connectedhomeip/src/lib/dnssd/minimal_mdns/records/tests \
Middlewares/Third_Party/connectedhomeip/src/lib/dnssd/minimal_mdns/responders \
Middlewares/Third_Party/connectedhomeip/src/lib/dnssd/minimal_mdns/responders/tests \
Middlewares/Third_Party/connectedhomeip/src/lib/dnssd/minimal_mdns/tests \
Middlewares/Third_Party/connectedhomeip/src/lib/dnssd/platform/tests \
Middlewares/Third_Party/connectedhomeip/src/lib/dnssd/tests \
Middlewares/Third_Party/connectedhomeip/src/lib/format \
Middlewares/Third_Party/connectedhomeip/src/lib/format/tests \
Middlewares/Third_Party/connectedhomeip/src/lib/shell \
Middlewares/Third_Party/connectedhomeip/src/lib/shell/commands \
Middlewares/Third_Party/connectedhomeip/src/lib/shell/tests \
Middlewares/Third_Party/connectedhomeip/src/lib/support \
Middlewares/Third_Party/connectedhomeip/src/lib/support/jsontlv \
Middlewares/Third_Party/connectedhomeip/src/lib/support/logging \
Middlewares/Third_Party/connectedhomeip/src/lib/support/tests \
Middlewares/Third_Party/connectedhomeip/src/lib/support/verhoeff \
Middlewares/Third_Party/connectedhomeip/src/messaging \
Middlewares/Third_Party/connectedhomeip/src/messaging/tests \
Middlewares/Third_Party/connectedhomeip/src/messaging/tests/echo \
Middlewares/Third_Party/connectedhomeip/src/messaging/tests/java \
Middlewares/Third_Party/connectedhomeip/src/platform \
Middlewares/Third_Party/connectedhomeip/src/platform/FreeRTOS \
Middlewares/Third_Party/connectedhomeip/src/platform/OpenThread \
Middlewares/Third_Party/connectedhomeip/src/platform/logging/impl/android \
Middlewares/Third_Party/connectedhomeip/src/platform/logging/impl/stdio \
Middlewares/Third_Party/connectedhomeip/src/platform/logging/impl/stdio/darwin \
Middlewares/Third_Party/connectedhomeip/src/platform/stm32/stm32wb \
Middlewares/Third_Party/connectedhomeip/src/protocols \
Middlewares/Third_Party/connectedhomeip/src/protocols/bdx \
Middlewares/Third_Party/connectedhomeip/src/protocols/bdx/tests \
Middlewares/Third_Party/connectedhomeip/src/protocols/echo \
Middlewares/Third_Party/connectedhomeip/src/protocols/interaction_model \
Middlewares/Third_Party/connectedhomeip/src/protocols/interaction_model/tests \
Middlewares/Third_Party/connectedhomeip/src/protocols/secure_channel \
Middlewares/Third_Party/connectedhomeip/src/protocols/secure_channel/tests \
Middlewares/Third_Party/connectedhomeip/src/protocols/user_directed_commissioning \
Middlewares/Third_Party/connectedhomeip/src/protocols/user_directed_commissioning/tests \
Middlewares/Third_Party/connectedhomeip/src/setup_payload \
Middlewares/Third_Party/connectedhomeip/src/setup_payload/tests \
Middlewares/Third_Party/connectedhomeip/src/system \
Middlewares/Third_Party/connectedhomeip/src/system/tests \
Middlewares/Third_Party/connectedhomeip/src/tracing/json \
Middlewares/Third_Party/connectedhomeip/src/tracing/perfetto \
Middlewares/Third_Party/connectedhomeip/src/tracing \
Middlewares/Third_Party/connectedhomeip/src/tracing/tests \
Middlewares/Third_Party/connectedhomeip/src/transport \
Middlewares/Third_Party/connectedhomeip/src/transport/raw \
Middlewares/Third_Party/connectedhomeip/src/transport/raw/tests \
Middlewares/Third_Party/connectedhomeip/src/transport/retransmit/tests \
Middlewares/Third_Party/connectedhomeip/src/transport/tests \
Middlewares/Third_Party/connectedhomeip/zzz_generated/app-common/zap-generated/attributes \
Middlewares/Third_Party/connectedhomeip/zzz_generated/app-common/zap-generated \
Middlewares/Third_Party/mbedtls/library \
Middlewares/Third_Party/mbedtls/programs/aes \
Middlewares/Third_Party/mbedtls/programs/cipher \
Middlewares/Third_Party/mbedtls/programs/fuzz \
Middlewares/Third_Party/mbedtls/programs/hash \
Middlewares/Third_Party/mbedtls/programs/pkey \
Middlewares/Third_Party/mbedtls/programs/random \
Middlewares/Third_Party/mbedtls/programs/ssl \
Middlewares/Third_Party/mbedtls/programs/test \
Middlewares/Third_Party/mbedtls/programs/test/cmake_package \
Middlewares/Third_Party/mbedtls/programs/test/cmake_package_install \
Middlewares/Third_Party/mbedtls/programs/test/cmake_subproject \
Middlewares/Third_Party/mbedtls/programs/util \
Middlewares/Third_Party/mbedtls/programs \
Middlewares/Third_Party/mbedtls/programs/x509 \
Middlewares/Third_Party/mbedtls/tests/src \
Middlewares/Third_Party/mbedtls/tests/src/drivers \
Middlewares/Third_Party/mbedtls/tests/src/test_helpers \
Middlewares/Third_Party/nlassert/tests \
Middlewares/Third_Party/nlio/tests \
STM32_WPAN/App \
STM32_WPAN/Target \
Utilities/Fonts \
Utilities/lpm/tiny_lpm \

